# Set Server port
server:
  port: 8080
  # Set context path
  servlet:
    context-path: /library-event-producer

#Set Swagger properties
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

# Set application name
spring:
  application:
    name: library-event-producer
  #Set active profile
  profiles:
    active: local

---
spring:
  profiles: local
  # Set Embedded Mongo version and features
  mongodb:
    embedded:
      version: 4.0.2
      features: ONLY_WITH_SSL, ONLY_WINDOWS_2008_SERVER, NO_HTTP_INTERFACE_ARG, ONLY_64_BIT

  # Set MongoDB name and port
  data:
    mongodb:
      database: library-event-producer
      port: 56686

  # Add Kafka Configurations
  kafka:
    bootstrap-servers: 'localhost:9092,localhost:9094'

---
spring:
  profiles: dev

  # Add MongoDB Configurations
  data:
    mongodb:
      database: library-event-producer
      port: 56688

  # Add Kafka Configurations
  kafka:
    bootstrap-servers: 'localhost:9092, localhost:9094'

---
spring:
  profiles: prod

  data:
    mongodb:
      database: library-event-producer
      port: 56688

  # Add Kafka Configurations
  kafka:
    bootstrap-servers: 'localhost:9092, localhost:9094'