package org.fourstack.springkafkaproducer.codetype;

public enum StdDepartment {
    ELECTRONICS_AND_COMMUNICATION,
    COMPUTER_SCIENCE,
    ELECTRICAL_AND_ELECTRONICS,
    MECHANICAL_ENGINEERING,
    CIVIL_ENGINEERING,
    TELECOMMUNICATION,
    INFORMATION_SCIENCE,
    INDUSTRIAL_MANAGEMENT
}
