#Set Server Port
server:
  port: 8082
  #Set context path
  servlet:
    context-path: /library-event-consumer

# Set application name
spring:
  application:
    name: library-event-consumer

  #Set active profile
  profiles:
    active: local

  # Set Embedded Mongo version and features
  mongodb:
    embedded:
      version: 4.0.2
      features:
        - ONLY_WITH_SSL
        - ONLY_WINDOWS_2008_SERVER
        - NO_HTTP_INTERFACE_ARG
        - ONLY_64_BIT
  # Set Database name and port
  data:
    mongodb:
      database: library-event-consumer
      port: 56684

---

spring:
  config:
    activate:
      on-profile: local

  # Add Kafka Configuration
  kafka:
    bootstrap-servers: 'localhost:9092'
    topic:
      library-events: library-events
      retry: library-events.retry
      dlt: library-events.DLT
    consumer:
      group:
        library-events-consumer-grp: library-events-consumer-group


---

spring:
  config:
    activate:
      on-profile: dev

  # Add Kafka Configuration
  kafka:
    bootstrap-servers: 'localhost:9092'

---

spring:
  config:
    activate:
      on-profile: prod

  # Add Kafka Configuration
  kafka:
    bootstrap-servers: 'localhost:9094'
    ssl:
      trust-store-location: file:D:\softwares\kafka_2.12-3.2.3\ssl\client.trustore.jks
      trust-store-password: KafkaSSL
      key-store-location: file:D:\softwares\kafka_2.12-3.2.3\ssl\client.keystore.jks
      key-store-password: KafkaSSL
    properties:
      acks: all
      retries: 10
      retry.backoff.ms: 1000
      security:
        protocol: SSL
      ssl.endpoint.identification.algorithm: