#Set Server port
server:
  port: 8082
  #Set context path
  servlet:
    context-path: /kafka-consumer-app

# Set application name
spring:
  application:
    name: kafka-consumer-app

  #Set Embedded Mongo version and fetaures
  mongodb:
    embedded:
      version: 4.0.2
      features: ONLY_WITH_SSL, ONLY_WINDOWS_2008_SERVER, NO_HTTP_INTERFACE_ARG, ONLY_64BIT

  # Set Database name and port
  data:
    mongodb:
      database: kafka-consumer-app
      port: 56682

  # Add Kafka Configuration
  kafka:
    bootstrap-servers: 'localhost:9092', 'localhost:9094', 'localhost:9096'
    consumer:
      properties:
        # Add Trusted packages to consume the all type of Model data
        spring.json.trusted.packages: '*'

# Properties to hold topic and group names
kafka:
  topics:
    flink-data-topic: flink-data-topic
    emp-list-topic: emp-list-topic
    student-list-topic: student-list-topic
  groups:
    flink-data-group: flink-data-group
    employee-data: employee-data
    student-data: student-data